services:
  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    environment:
      - DJANGO__DEBUG=${DJANGO__DEBUG}
      - DJANGO__SECRET_KEY=${DJANGO__SECRET_KEY}
    volumes:
      - ./webapp:/app
    ports:
      - "0.0.0.0:80:8000"

    restart: on-failure
